"""UERANSIM UE Lifecycle and Process Supervisor.

Supports:
- Generating 3GPP-compliant UERANSIM UE configuration YAMLs.
- Spawning and supervising individual nr-ue background processes.
- Querying session telemetry via nr-cli and Linux network interface inspection.
- Graceful termination and isolation in config/managed/ directory.
- Local host execution (ROLE=ue-agent) and remote SSH execution.
"""

from typing import Dict, List, Optional, Any
import json
import logging
import os
import re
import subprocess
import time

from src.models import (
    OrchestratedEndpoint,
    SecurityConfig,
    SliceConfig,
    QoSConfig,
)

logger = logging.getLogger("UERANSIMClient")


class UERANSIMClient:
    """Manages UERANSIM UE configurations and nr-ue daemon processes."""

    def __init__(
        self,
        ueransim_dir: Optional[str] = None,
        ssh_host: Optional[str] = None,
        gnb_search_list: Optional[List[str]] = None,
        mcc: str = "999",
        mnc: str = "70",
        mock_mode: bool = False,
    ):
        self.ueransim_dir = ueransim_dir or os.environ.get("UERANSIM_DIR", "/home/ubuntu/UERANSIM")
        self.ssh_host = ssh_host or os.environ.get("RAN_SSH_HOST", "jsuzanne@152.236.5.67")
        self.gnb_search_list = gnb_search_list or ["10.10.10.2"]
        self.mcc = mcc
        self.mnc = mnc
        self.mock_mode = mock_mode or (os.environ.get("MOCK_MODE", "false").lower() == "true")
        self._mock_processes: Dict[str, Dict[str, Any]] = {}

    def _exec_command(self, cmd: str) -> str:
        """Execute command locally if on RAN host, or over SSH if remote."""
        if self.mock_mode:
            return ""

        # Local execution on UERANSIM VM
        if os.environ.get("ROLE") in ("ue-agent", "all") or not self.ssh_host:
            res = subprocess.run(cmd, shell=True, capture_output=True, text=True)
            if res.returncode != 0 and "pkill" not in cmd:
                logger.error(f"Local command failed: {res.stderr.strip()}")
            return res.stdout.strip()

        # Remote execution over SSH
        ssh_cmd = [
            "ssh",
            "-o", "BatchMode=yes",
            "-o", "ConnectTimeout=5",
            "-o", "StrictHostKeyChecking=accept-new",
            self.ssh_host,
            cmd,
        ]
        res = subprocess.run(ssh_cmd, capture_output=True, text=True)
        if res.returncode != 0 and "pkill" not in cmd:
            logger.error(f"SSH command failed on {self.ssh_host}: {res.stderr.strip()}")
        return res.stdout.strip()

    def generate_ue_yaml(self, endpoint: OrchestratedEndpoint) -> str:
        """Generate UERANSIM YAML configuration for an endpoint."""
        imsi = str(endpoint.imsi)
        supi = f"imsi-{imsi}" if not imsi.startswith("imsi-") else imsi
        k = endpoint.security.k.upper()
        op = endpoint.security.op.upper()
        op_type = endpoint.security.op_type.upper()
        amf = endpoint.security.amf
        imei = endpoint.imei
        # Default imeisv with '01' if 15 digits
        imeisv = f"{imei}01" if len(imei) == 15 else imei

        sst = endpoint.slice.sst
        sd_entry = f"    sd: {endpoint.slice.sd}\n" if endpoint.slice.sd else ""

        gnb_entries = "\n".join([f"  - {ip}" for ip in self.gnb_search_list])

        yaml_content = f"""# UERANSIM Config for {endpoint.device_name} ({endpoint.vertical_id})
# Auto-generated by Prisma 5G Orchestrator
supi: '{supi}'
mcc: '{self.mcc}'
mnc: '{self.mnc}'
protectionScheme: 0
homeNetworkPublicKey: '5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650'
homeNetworkPublicKeyId: 1
routingIndicator: '0000'

key: '{k}'
op: '{op}'
opType: '{op_type}'
amf: '{amf}'
imei: '{imei}'
imeiSv: '{imeisv}'

tunNetmask: '255.255.255.0'
useNamespace: false

gnbSearchList:
{gnb_entries}

uacAic:
  mps: false
  mcs: false

uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

sessions:
  - type: 'IPv4'
    apn: '{endpoint.apn}'
    slice:
      sst: {sst}
{sd_entry}configured-nssai:
  - sst: {sst}
{sd_entry}default-nssai:
  - sst: {sst}
{sd_entry}integrity:
  IA1: true
  IA2: true
  IA3: true

ciphering:
  EA1: true
  EA2: true
  EA3: true

integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
"""
        return yaml_content

    def start_ue(self, endpoint: OrchestratedEndpoint) -> Dict[str, Any]:
        """Deploy YAML configuration and spawn nr-ue process."""
        imsi = str(endpoint.imsi)
        yaml_content = self.generate_ue_yaml(endpoint)

        if self.mock_mode:
            self._mock_processes[imsi] = {
                "imsi": imsi,
                "pid": 99999,
                "status": "running",
                "interface": "uesimtun1",
                "config_path": f"/tmp/ue-{imsi}.yaml",
            }
            return self._mock_processes[imsi]

        # 1. Create managed config directory if missing
        managed_dir = f"{self.ueransim_dir}/config/managed"
        self._exec_command(f"sudo mkdir -p {managed_dir}")

        # 2. Write YAML config file safely
        config_path = f"{managed_dir}/ue-{imsi}.yaml"
        # Escape single quotes in yaml for shell
        escaped_yaml = yaml_content.replace("'", "'\\''")
        write_cmd = f"sudo bash -c 'cat << \"EOF\" > {config_path}\n{yaml_content}\nEOF'"
        self._exec_command(write_cmd)

        # 3. Terminate any previous instance for this IMSI
        self.stop_ue(imsi)

        # 4. Launch nr-ue in background
        log_path = f"/tmp/nr-ue-{imsi}.log"
        run_cmd = f"cd {self.ueransim_dir} && sudo nohup ./build/nr-ue -c {config_path} > {log_path} 2>&1 &"
        self._exec_command(run_cmd)

        # Allow process a moment to initialize
        time.sleep(1.0)
        status = self.get_ue_status(imsi)
        return status

    def stop_ue(self, imsi: str) -> bool:
        """Stop nr-ue process for this IMSI and remove managed config."""
        if self.mock_mode:
            self._mock_processes.pop(imsi, None)
            return True

        # Kill only this specific managed nr-ue instance
        kill_cmd = f"sudo pkill -f 'nr-ue.*ue-{imsi}.yaml' 2>/dev/null || true"
        self._exec_command(kill_cmd)

        # Remove config file
        rm_cmd = f"sudo rm -f {self.ueransim_dir}/config/managed/ue-{imsi}.yaml 2>/dev/null || true"
        self._exec_command(rm_cmd)
        return True

    def get_ue_status(self, imsi: str) -> Dict[str, Any]:
        """Check status of nr-ue process and query nr-cli for session telemetry."""
        if self.mock_mode:
            proc = self._mock_processes.get(imsi)
            if proc:
                return {
                    "imsi": imsi,
                    "running": True,
                    "pid": proc.get("pid"),
                    "interface": proc.get("interface", "uesimtun1"),
                    "pdu_status": "PS-ACTIVE",
                }
            return {"imsi": imsi, "running": False, "pdu_status": "STOPPED"}

        # Check running process
        ps_cmd = f"pgrep -f 'nr-ue.*ue-{imsi}.yaml' | head -n 1"
        pid_str = self._exec_command(ps_cmd)
        running = bool(pid_str and pid_str.isdigit())
        pid = int(pid_str) if running else None

        pdu_status = "UNKNOWN"
        interface_name = None
        assigned_ip = None

        if running:
            # Query nr-cli
            supi = f"imsi-{imsi}" if not imsi.startswith("imsi-") else imsi
            cli_cmd = f"sudo {self.ueransim_dir}/build/nr-cli {supi} --exec 'ps-list' 2>/dev/null || true"
            cli_out = self._exec_command(cli_cmd)
            if "PS-ACTIVE" in cli_out:
                pdu_status = "PS-ACTIVE"
                # Extract IP if present in nr-cli output
                ip_match = re.search(r"address:\s*([0-9.]+)", cli_out)
                if ip_match:
                    assigned_ip = ip_match.group(1)

        return {
            "imsi": imsi,
            "running": running,
            "pid": pid,
            "pdu_status": pdu_status,
            "interface": interface_name,
            "assigned_ip": assigned_ip,
        }

    def list_active_ues(self) -> List[Dict[str, Any]]:
        """List all active managed UEs running on UERANSIM."""
        if self.mock_mode:
            return list(self._mock_processes.values())

        cmd = "ps aux | grep -E 'nr-ue.*config/managed' | grep -v grep || true"
        out = self._exec_command(cmd)
        results = []
        if out:
            for line in out.splitlines():
                match = re.search(r"ue-([0-9]+)\.yaml", line)
                if match:
                    imsi = match.group(1)
                    results.append(self.get_ue_status(imsi))
        return results
