"""UERANSIM UE Lifecycle and Process Supervisor.

Supports:
- Generating 3GPP-compliant UERANSIM UE configuration YAMLs.
- Spawning and supervising individual nr-ue background processes.
- Querying session telemetry via nr-cli and Linux network interface inspection.
- Graceful termination and isolation in config/managed/ directory.
- Local host execution (ROLE=ue-agent) and remote SSH execution.
"""

from typing import Dict, List, Optional, Any
import json
import logging
import os
import re
import subprocess
import time

from src.models import (
    OrchestratedEndpoint,
    SecurityConfig,
    SliceConfig,
    QoSConfig,
)

logger = logging.getLogger("UERANSIMClient")


class UERANSIMClient:
    """Manages UERANSIM UE configurations and nr-ue daemon processes."""

    def __init__(
        self,
        ueransim_dir: Optional[str] = None,
        ssh_host: Optional[str] = None,
        gnb_search_list: Optional[List[str]] = None,
        mcc: str = "999",
        mnc: str = "70",
        mock_mode: bool = False,
    ):
        self.ueransim_dir = ueransim_dir or os.environ.get("UERANSIM_DIR", "/home/ubuntu/UERANSIM")
        self.ssh_host = ssh_host or os.environ.get("RAN_SSH_HOST", "jsuzanne@152.236.5.67")
        self.gnb_search_list = gnb_search_list or ["10.10.10.2"]
        self.mcc = mcc
        self.mnc = mnc
        self.mock_mode = mock_mode or (os.environ.get("MOCK_MODE", "false").lower() == "true")
        self._mock_processes: Dict[str, Dict[str, Any]] = {}

    def _exec_command(self, cmd: str) -> str:
        """Execute command locally if on RAN host, or over SSH if remote."""
        if self.mock_mode:
            return ""

        try:
            # Local execution on UERANSIM VM
            if os.environ.get("ROLE") in ("ue-agent", "all") or not self.ssh_host:
                res = subprocess.run(cmd, shell=True, capture_output=True, text=True)
                if res.returncode != 0 and "pkill" not in cmd:
                    logger.warning(f"Local command failed: {res.stderr.strip()}")
                return res.stdout.strip()

            # Remote execution over SSH
            ssh_cmd = [
                "ssh",
                "-o", "BatchMode=yes",
                "-o", "ConnectTimeout=5",
                "-o", "StrictHostKeyChecking=accept-new",
                self.ssh_host,
                cmd,
            ]
            res = subprocess.run(ssh_cmd, capture_output=True, text=True)
            if res.returncode != 0 and "pkill" not in cmd:
                logger.warning(f"SSH command failed on {self.ssh_host}: {res.stderr.strip()}")
            return res.stdout.strip()
        except FileNotFoundError:
            logger.warning(f"SSH or shell utility not found when attempting command: {cmd}")
            return ""
        except Exception as e:
            logger.warning(f"Command execution exception ({cmd}): {e}")
            return ""

    def generate_ue_yaml(self, endpoint: OrchestratedEndpoint) -> str:
        """Generate UERANSIM YAML configuration for an endpoint."""
        imsi = str(endpoint.imsi)
        supi = f"imsi-{imsi}" if not imsi.startswith("imsi-") else imsi
        clean_imsi = re.sub(r"\D", "", imsi)
        if len(clean_imsi) >= 5:
            mcc = clean_imsi[:3]
            mnc = clean_imsi[3:5]
        else:
            mcc = self.mcc
            mnc = self.mnc

        k = endpoint.security.k.upper()
        op = endpoint.security.op.upper()
        op_type = endpoint.security.op_type.upper()
        amf = endpoint.security.amf
        imei = endpoint.imei
        # Ensure IMEISV is exactly 16 digits (TAC 8 + SNR 6 + SV 2)
        imeisv = f"{imei[:14]}01" if len(imei) >= 14 else f"{imei}01"

        sst = endpoint.slice.sst
        sd_session = f"\n      sd: {endpoint.slice.sd}" if endpoint.slice.sd else ""
        sd_nssai = f"\n    sd: {endpoint.slice.sd}" if endpoint.slice.sd else ""
        gnb_entries = "\n".join([f"  - {ip}" for ip in self.gnb_search_list])

        yaml_content = f"""# UERANSIM Config for {endpoint.device_name} ({endpoint.vertical_id})
# Auto-generated by Prisma 5G Orchestrator
supi: '{supi}'
mcc: '{mcc}'
mnc: '{mnc}'
protectionScheme: 0
homeNetworkPublicKey: '5a8d38864820197c3394b92613b20b91633cbd897119273bf8e4a6f4eec0a650'
homeNetworkPublicKeyId: 1
routingIndicator: '0000'

key: '{k}'
op: '{op}'
opType: '{op_type}'
amf: '{amf}'
imei: '{imei}'
imeiSv: '{imeisv}'

tunNetmask: '255.255.255.0'
useNamespace: false

gnbSearchList:
{gnb_entries}

uacAic:
  mps: false
  mcs: false

uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

sessions:
  - type: 'IPv4'
    apn: '{endpoint.apn}'
    slice:
      sst: {sst}{sd_session}

configured-nssai:
  - sst: {sst}{sd_nssai}

default-nssai:
  - sst: {sst}{sd_nssai}

integrity:
  IA1: true
  IA2: true
  IA3: true

ciphering:
  EA1: true
  EA2: true
  EA3: true

integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
"""
        return yaml_content

    def _write_file(self, file_path: str, content: str) -> None:
        """Write file locally or remotely over SSH using sudo tee."""
        if self.mock_mode:
            return
        if os.environ.get("ROLE") in ("ue-agent", "all") or not self.ssh_host:
            p = subprocess.run(["sudo", "tee", file_path], input=content, text=True, capture_output=True)
            if p.returncode != 0:
                logger.error(f"Failed to write local file {file_path}: {p.stderr}")
            return

        ssh_cmd = [
            "ssh",
            "-o", "BatchMode=yes",
            "-o", "ConnectTimeout=5",
            "-o", "StrictHostKeyChecking=accept-new",
            self.ssh_host,
            f"sudo mkdir -p $(dirname {file_path}) && sudo tee {file_path} > /dev/null",
        ]
        p = subprocess.run(ssh_cmd, input=content, text=True, capture_output=True)
        if p.returncode != 0:
            logger.error(f"Failed to write remote file {file_path} on {self.ssh_host}: {p.stderr}")

    def start_ue(self, endpoint: OrchestratedEndpoint) -> Dict[str, Any]:
        """Deploy YAML configuration and spawn nr-ue process."""
        imsi = str(endpoint.imsi)
        yaml_content = self.generate_ue_yaml(endpoint)

        if self.mock_mode:
            self._mock_processes[imsi] = {
                "imsi": imsi,
                "pid": 99999,
                "status": "running",
                "interface": "uesimtun1",
                "config_path": f"/tmp/ue-{imsi}.yaml",
            }
            return self._mock_processes[imsi]

        # 1. Terminate any previous instance for this IMSI
        self.stop_ue(imsi)

        # 2. Write YAML config file safely via stdin
        config_path = f"{self.ueransim_dir}/config/managed/ue-{imsi}.yaml"
        self._write_file(config_path, yaml_content)

        # 3. Launch nr-ue in background via disowned subshell
        log_path = f"/tmp/nr-ue-{imsi}.log"
        run_cmd = f"sudo bash -c 'cd {self.ueransim_dir} && (nohup ./build/nr-ue -c {config_path} > {log_path} 2>&1 </dev/null &)'"
        self._exec_command(run_cmd)

        # Allow process a moment to initialize
        time.sleep(1.5)
        status = self.get_ue_status(imsi)
        status["initial_logs"] = self.get_ue_logs(imsi, lines=25).get("logs", "")
        return status

    def stop_ue(self, imsi: str) -> bool:
        """Stop nr-ue process for this IMSI and remove managed config."""
        if self.mock_mode:
            self._mock_processes.pop(imsi, None)
            return True

        # Kill only this specific managed nr-ue instance
        kill_cmd = f"sudo pkill -f 'nr-ue.*ue-{imsi}.yaml' 2>/dev/null || true"
        self._exec_command(kill_cmd)

        # Remove config file
        rm_cmd = f"sudo rm -f {self.ueransim_dir}/config/managed/ue-{imsi}.yaml 2>/dev/null || true"
        self._exec_command(rm_cmd)
        return True

    def get_ue_logs(self, imsi: str, lines: int = 50) -> Dict[str, Any]:
        """Fetch the last N lines of logs for a given UE from the RAN host."""
        clean_imsi = re.sub(r"\D", "", str(imsi))
        log_path = f"/tmp/nr-ue-{clean_imsi}.log"
        if self.mock_mode:
            mock_logs = (
                f"[2026-10-02 12:00:00.100] [rrc] [info] Selected cell plmn[999/70] tac[1] category[SUITABLE]\n"
                f"[2026-10-02 12:00:00.102] [rrc] [info] RRC connection established\n"
                f"[2026-10-02 12:00:00.105] [nas] [info] Initial Registration is successful\n"
                f"[2026-10-02 12:00:00.110] [nas] [info] PDU Session establishment is successful PSI[1]\n"
                f"[2026-10-02 12:00:00.112] [app] [info] Connection setup for PDU session[1] is successful, TUN interface[uesimtun1, 10.45.0.18] is up."
            )
            return {"imsi": clean_imsi, "log_path": log_path, "logs": mock_logs, "lines": lines}

        cmd = f"sudo tail -n {lines} {log_path} 2>/dev/null || echo 'No log file found at {log_path}'"
        log_text = self._exec_command(cmd)
        return {
            "imsi": clean_imsi,
            "log_path": log_path,
            "logs": log_text,
            "lines": lines,
        }

    def get_ue_status(self, imsi: str) -> Dict[str, Any]:
        """Check status of nr-ue process, log status, and query nr-cli for session telemetry."""
        clean_imsi = re.sub(r"\D", "", str(imsi))
        if self.mock_mode:
            proc = self._mock_processes.get(clean_imsi)
            if proc:
                return {
                    "imsi": clean_imsi,
                    "running": True,
                    "pid": proc.get("pid"),
                    "interface": proc.get("interface", "uesimtun1"),
                    "assigned_ip": "10.45.0.18",
                    "pdu_status": "PS-ACTIVE",
                }
            return {"imsi": clean_imsi, "running": False, "pdu_status": "STOPPED"}

        # Check running process
        ps_cmd = f"pgrep -f 'nr-ue.*ue-{clean_imsi}.yaml' | head -n 1"
        pid_str = self._exec_command(ps_cmd)
        running = bool(pid_str and pid_str.isdigit())
        pid = int(pid_str) if running else None

        pdu_status = "UNKNOWN"
        interface_name = None
        assigned_ip = None

        # Inspect log file for connection state & TUN info
        log_path = f"/tmp/nr-ue-{clean_imsi}.log"
        tail_cmd = f"sudo tail -n 30 {log_path} 2>/dev/null || true"
        tail_out = self._exec_command(tail_cmd)

        if "TUN interface[" in tail_out:
            tun_match = re.search(r"TUN interface\[([a-zA-Z0-9]+),\s*([0-9.]+)\]", tail_out)
            if tun_match:
                interface_name = tun_match.group(1)
                assigned_ip = tun_match.group(2)
                pdu_status = "PS-ACTIVE"
        elif "PDU Session establishment is successful" in tail_out:
            pdu_status = "PS-ACTIVE"
        elif "FIVEG_SERVICES_NOT_ALLOWED" in tail_out or "Registration reject" in tail_out:
            pdu_status = "REJECTED (PLMN/Auth)"
        elif running:
            pdu_status = "CONNECTING"
        else:
            pdu_status = "STOPPED"

        if running and pdu_status != "PS-ACTIVE":
            # Query nr-cli fallback
            supi = f"imsi-{clean_imsi}"
            cli_cmd = f"sudo {self.ueransim_dir}/build/nr-cli {supi} --exec 'ps-list' 2>/dev/null || true"
            cli_out = self._exec_command(cli_cmd)
            if "PS-ACTIVE" in cli_out:
                pdu_status = "PS-ACTIVE"
                ip_match = re.search(r"address:\s*([0-9.]+)", cli_out)
                if ip_match:
                    assigned_ip = ip_match.group(1)

        return {
            "imsi": clean_imsi,
            "running": running,
            "pid": pid,
            "pdu_status": pdu_status,
            "interface": interface_name,
            "assigned_ip": assigned_ip,
            "log_path": log_path,
        }

    def list_active_ues(self) -> List[Dict[str, Any]]:
        """List all active managed UEs running on UERANSIM."""
        if self.mock_mode:
            return list(self._mock_processes.values())

        cmd = "ps aux | grep -E 'nr-ue.*config/managed' | grep -v grep || true"
        out = self._exec_command(cmd)
        results = []
        if out:
            for line in out.splitlines():
                match = re.search(r"ue-([0-9]+)\.yaml", line)
                if match:
                    imsi = match.group(1)
                    results.append(self.get_ue_status(imsi))
        return results

    def get_active_tun_interfaces(self) -> List[Dict[str, str]]:
        """List active uesimtun network interfaces and their allocated IPs on the RAN host."""
        if self.mock_mode:
            return [{"interface": "uesimtun0", "status": "UNKNOWN", "ip": "10.45.0.3", "cidr": "10.45.0.3/24"}]

        out = self._exec_command("ip -br a | grep uesimtun || true")
        interfaces = []
        if out:
            for line in out.splitlines():
                parts = line.split()
                if len(parts) >= 3:
                    iface = parts[0]
                    state = parts[1]
                    ip_cidr = parts[2]
                    ip = ip_cidr.split("/")[0] if "/" in ip_cidr else ip_cidr
                    interfaces.append({"interface": iface, "status": state, "ip": ip, "cidr": ip_cidr})
        return interfaces
